- name: Install a list of packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - libuhd-dev
    - libuhd003
    - uhd-host
    - cmake
    - libfftw3-dev
    - libmbedtls-dev
    - libboost-program-options-dev
    - libconfig++-dev
    - libsctp-dev
